import { ReportData } from "../models/ReportData";

/**
 * LaTeX Template String with placeholders
 */
const BASE_LATEX = `
\\documentclass[a4paper,11pt]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[left=2cm,right=2cm,top=2.5cm,bottom=2.5cm]{geometry}
\\usepackage{graphicx}
\\usepackage{xcolor}
\\usepackage{helvet}
\\usepackage{fancyhdr}
\\usepackage{titlesec}
\\usepackage{tabularx}
\\usepackage{enumitem}
\\usepackage{tikz}

\\definecolor{themeblue}{HTML}{007AFF}
\\definecolor{headerdark}{HTML}{0B0F2A}
\\definecolor{riskred}{HTML}{FA114F}
\\definecolor{textgray}{HTML}{666666}

\\renewcommand{\\familydefault}{\\sfdefault}

\\pagestyle{fancy}
\\fancyhf{}

\\newcommand{\\reportheader}[3]{
    \\begin{tikzpicture}[remember picture,overlay]
        \\fill[themeblue] (current page.north west) rectangle ([yshift=-1cm]current page.north east);
    \\end{tikzpicture}
    \\vspace{0.5cm}
    \\noindent
    \\begin{tabularx}{\\textwidth}{@{}l X r@{}}
        \\textbf{FORENSIQ.AI} & & 
        \\begin{tabular}[b]{r@{}}
            \\color{riskred} \\textbf{\\uppercase{Final Verdict: #1}} \\\\
            \\color{textgray} \\scriptsize CASE ID: #2 \\\\
            \\color{textgray} \\scriptsize ISSUED: #3
        \\end{tabular}
    \\end{tabularx}
    \\vspace{0.8cm}
    \\noindent{\\huge \\textbf{Forensic Extraction Report}} \\\\
    \\noindent\\color{textgray}\\small Generated by ForensIQ.ai Auto-Neural Engine
    \\vspace{0.8cm}
}

\\titleformat{\\section}{\\color{textgray}\\normalsize\\bfseries\\uppercase}{}{0em}{}[\\titlerule]
\\titlespacing*{\\section}{0pt}{1.5ex}{1ex}

\\begin{document}

\\reportheader{__VERDICT__}{__CASEID__}{__DATE__}

\\section{1.0 Executive Summary}
Analysis of the asset, \\textit{__FILENAME__}, has confirmed severe structural compromise. The investigative framework has isolated typographical injections and layering anomalies consistent with synthetic forgery. These findings collectively render the document as Compromised and unsuitable for standard verification workflows.

\\vspace{1cm}

\\section{2.0 Technical Provenance}
\\noindent
\\begin{tabularx}{\\textwidth}{@{}l X@{}}
    \\textbf{Source Filename:} & __FILENAME__ \\\\
    \\textbf{Binary Size:} & __SIZE__ \\\\
    \\textbf{Architecture:} & __ARCH__ \\\\
    \\textbf{MIME Type:} & __MIME__ \\\\
    \\textbf{SHA-256:} & __SHA256__ \\\\
\\end{tabularx}

\\vspace{1cm}

\\section{3.0 Forensic Diagnostic Index}
\\begin{itemize}[leftmargin=*, label={}]
    __ANOMALIES__
\\end{itemize}

\\vfill

\\noindent
\\begin{tabularx}{\\textwidth}{@{}X r@{}}
    & \\begin{tabular}{c}
        \\textit{\\huge __INVESTIGATOR__} \\\\ \\hline
        \\textbf{Authorized Investigator} \\\\
        \\scriptsize Credential ID: __INVESTIGATORID__
    \\end{tabular}
\\end{tabularx}

\\vspace{1.5cm}

\\begin{tikzpicture}[remember picture,overlay]
    \\fill[headerdark] (current page.south west) rectangle ([yshift=1.5cm]current page.south east);
    \\draw[themeblue, line width=4pt] (current page.south west) ++(0,1.5cm) -- ++(\\paperwidth,0);
    \\node[anchor=west, text=white, opacity=0.4] at ([shift={(2cm,0.75cm)}]current page.south west) {\\small \\textbf{\\uppercase{ForensIQ Forensic Division}}};
    \\node[anchor=east, text=white, opacity=0.3] at ([shift={(-2cm,0.75cm)}]current page.south east) {\\scriptsize Page 01 of 01 · Strictly Confidential};
\\end{tikzpicture}

\\end{document}
`;

/**
 * Maps ReportData to a compiled LaTeX string
 */
export function generateLatexFromData(data: ReportData): string {
  let tex = BASE_LATEX;

  // Metadata
  tex = tex.replace(/__VERDICT__/g, data.metadata.verdict);
  tex = tex.replace(/__CASEID__/g, data.metadata.caseId);
  tex = tex.replace(/__DATE__/g, data.metadata.date);

  // Provenance
  tex = tex.replace(/__FILENAME__/g, data.provenance.filename.replace(/_/g, '\\_'));
  tex = tex.replace(/__SIZE__/g, data.provenance.size);
  tex = tex.replace(/__ARCH__/g, data.provenance.architecture);
  tex = tex.replace(/__MIME__/g, data.provenance.mime.replace(/\//g, '\\/'));
  tex = tex.replace(/__SHA256__/g, data.provenance.hashes.sha256);

  // Anomalies
  const anomaliesTex = data.anomalies.map(a => `
    \\item \\color{riskred} \\textbullet \\textbf{ ${a.title} (${a.severity})} \\\\
    ${a.detail} \\\\
    \\textit{Location: ${a.location}} \\vspace{0.8cm}
  `).join('\n');
  
  tex = tex.replace("__ANOMALIES__", anomaliesTex);

  // Investigator
  tex = tex.replace("__INVESTIGATOR__", data.investigator.name);
  tex = tex.replace("__INVESTIGATORID__", data.investigator.id);

  return tex;
}

/**
 * Downloads the LaTeX source file as a .tex blob 
 */
export function downloadLatexSource(data: ReportData) {
  const content = generateLatexFromData(data);
  const blob = new Blob([content], { type: 'text/x-tex' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `ForensIQ_Report_${data.metadata.caseId.replace(/\s+/g, '_')}.tex`;
  link.click();
}
